
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'vbi_zoho_people'
version: '1.0.0'


# This setting configures which "profile" dbt uses for this project.
profile: 'visualbi_zoho_oa_dw'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  vbi_zoho_people:
      # Applies to all files under models/example/
      analytics:
        schema: analytics
        tags: 'analytics'
        materialized : 'table'
      stg_zoho:
        schema: stg_zoho
        tags: 'stage_zoho'
        materialized : 'view'
      raw_zoho:
        tags: 'deltaload'
        materialized : 'table'
      stg_oa_api:
        schema: stg_openair
        tags: 'stage_openair_api'
        materialized : 'table'
      stg_oa_odata:
        schema: stg_openair_odata
        tags: 'stage_openair_odata'
        materialized : 'table'

vars:
    zoho_form_list : ['employee',
                      'Project_Department_Changes',
                      'designation',
                      'Designation_Change_Request',
                      'Intercompany_Transfer',
                      'Reporting_Changes']